# Generated by Django 5.0.6 on 2024-05-14 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('Development Project', 'Development Project'), ('Off Plan Project', 'Offplan Project'), ('Ready Project', 'Ready Project')], default='Development Project', max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('extimated_price', models.IntegerField(blank=True)),
                ('featured', models.BooleanField(blank=True, default=True)),
                ('units', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('video_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
