# Generated by Django 5.0.4 on 2024-07-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='photo_main',
            new_name='project_logo',
        ),
    ]
