# Generated by Django 5.0.6 on 2024-05-14 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('available_day', models.DateField(default=datetime.datetime(2024, 5, 15, 12, 14, 56, 613503))),
                ('message', models.TextField()),
            ],
        ),
    ]
